//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// ${agent_name} agent pkg
//
`ifndef ${agent_name.upper()}_AGENT_PKG_SV
`define ${agent_name.upper()}_AGENT_PKG_SV
`timescale 1ns/1ps
package ${agent_name}_agent_pkg;

  import uvm_pkg::*;
`include "uvm_macros.svh"
//`include "typedefine.svh"

//  import seq_item_pkg::*;

//components
`include "${agent_name}_seq_item.svh"
`include "${agent_name}_sequencer.svh"
`include "${agent_name}_driver.svh"
`include "${agent_name}_monitor.svh"

//agent
`include "${agent_name}_agent_cfg.svh"  
`include "${agent_name}_agent.svh"

endpackage // ${agent_name}_agent_pkg
`endif //${agent_name.upper()}_AGENT_PKG_SV
