//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// spi agent configuration
//
`ifndef SPI_AGENT_CFG_SVH
`define SPI_AGENT_CFG_SVH
class spi_agent_cfg extends uvm_object;
  `uvm_object_utils(spi_agent_cfg)

  bit ACTIVE = 1;

  virtual apb_if apb_vif;
  virtual mac_if mac_vif;

  function new(string name = "spi_agent_cfg");
    super.new(name);
  endfunction // new
  
  
endclass // spi_agent_cfg
`endif //SPI_AGENT_CFG_SVH
