//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// spi agent pkg
//
`ifndef SPI_AGENT_PKG_SV
`define SPI_AGENT_PKG_SV
`timescale 1ns/1ps
package spi_agent_pkg;

  import uvm_pkg::*;
`include "uvm_macros.svh"
//`include "typedefine.svh"

//  import seq_item_pkg::*;

//components
`include "spi_seq_item.svh"
`include "spi_sequencer.svh"
`include "spi_driver.svh"
`include "spi_monitor.svh"

//agent
`include "spi_agent_cfg.svh"  
`include "spi_agent.svh"

endpackage // spi_agent_pkg
`endif //SPI_AGENT_PKG_SV
