//
//Note:
//This file is generated by Mako Template
//${env_name}_env_pkg
//

`ifndef ${env_name}_ENV_PKG
`define ${env_name}_ENV_PKG

package ${env_name}_env_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

   `include "../${env_name}_env/${scoreboard}_scoreboard.svh"
   `include "../${env_name}_env/${vsqr_name}.svh"
   `include "../${env_name}_env/${env_name}_env.svh"
   `include "../${env_name}_env/${env_name}_basic_test.svh"

endpackage: ${env_name}_env_pkg
`endif //${env_name}_ENV_PKG