//
//Note:
//This file is generated by Mako Template
//${scoreboard}_scoreboard
//
`ifndef ${scoreboard.upper()}_SCOREBOARD_SVH
`define ${scoreboard.upper()}_SCOREBOARD_SVH
class ${scoreboard}_scoreboard extends uvm_scoreboard;
  `uvm_component_utils(${scoreboard}_scoreboard)

  %for i in seq_item:
  uvm_block_get_block_port #({i}_seq_item) ${i}_port;
  %endfor

  %for i in seq_item:
  ${i}_seq_item ${i}_queue[$];
  %endfor

  extern virtual function void new(string name = "${scoreboard}_scoreboard",uvm_component parent = null);
  extern virtual function void build_phase(uvm_phase phase);
  extern virtual function void run_phase(uvm_phase phase);

endclass: ${scoreboard}_scoreboard

function void ${scoreboard}_scoreboard::new(string name = "${scoreboard}_scoreboard",uvm_component parent = null);
  super.new(name,parent);
endfunction:new

function void ${scoreboard}_scoreboard::build_phase(uvm_phase phase);
  super.build_phase();

endfunction: build_phase

function void ${scoreboard}_scoreboard::run_phase(uvm_phase phase);
  super.run_phase(phase);

endfunction: run_phase
`endif //${scoreboard.upper()}_SCOREBOARD_SVH
