//
//Note:
//This file is generated by Mako Template
//${env_name}
//
`ifndef ${env_name.upper()}_ENV_SVH
`define ${env_name.upper()}_ENV_SVH
class ${env_name}_env extends uvm_env;
  `uvm_component_utils(${env_name}_env)

  %for i in interface:
  virtual ${i}_if ${i}_vif;
  %endfor

  %for i in agent:
  ${i}_agent ${i}_agt;
  %endfor

  ${scoreboard}_scoreboard ${scoreboard}_scb;
  ${coverage}_coverage ${coverage}_cvr;
  ${reg_model_name} p_rm;

  %for i in seq_item:
  uvm_tlm_analysis_fifo #(${i}_seq_item) ${i}_fifo;
  %endfor

  extern funtion new(string name = "${env_name}",uvm_component parent);
  extern function void build_phase(uvm_phase phase);
  extern function void connect_phase(uvm_phase phase);

endclass: ${env_name}_env

function ${env_name}::new(string name = "${env_name}_env",uvm_component parent);
  super.new(name, parent);
endfunction

function void ${env_name}_env::build_phase(uvm_phase phase);
  super.build_phase(phase);

  %for i in agent:
  ${i}_agt = ${i}_agent::type_id::creat("${i}_agt",this);
  ${i}_agt.is_active = UVM_ACTIVE;
  %endfor

  ${scoreboard}_scb = ${scoreboard}_scoreboard::type_id::creat("${scoreboard}_scb",this);
  ${coverage}_cvr = ${coverage}_coverage::type_id::create("${coverage}_cvr",this);
  p_rm = ${reg_model_name}::type_id::type_id::create("p_rm",this);

  %for i in seq_item:
  ${i}_fifo = new("${i}_fifo",this);
  %endfor

  %for i in interface:
  if(!uvm_config_db#(virtual ${i}_if)::get(this, "", "${i}_vif", ${i}_vif))
    `uvm_fatal("build_phase","No get ${i}_if!!!!")
  %endfor

endfunction:build_phase

function void ${env_name}_env::connect_phase(uvm_phase phase);
  super.connect_phase(phase);
endfunction:connect_phase
`endif //${env_name.upper()}_ENV_SVH