//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// spi testcases pkg
//

`ifndef SPI_TESTCASES_PKG
`define SPI_TESTCASES_PKG

package spi_testcases_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  `include "../spi_testcases/spi_basic_testcase.svh"

endpackage: spi_testcases_pkg
`endif //SPI_TESTCASES_PKG