//
//Note:
//This file is generated by Mako Template
//spi_test_top
//
`ifndef SPI_TEST_TOP_SV
`define SPI_TEST_TOP_SV
module spi_test_top;

  spi_if spi_vif;
  apb_if apb_vif;

  //add Dut top


  initial begin
    run_test();
  end

  initial begin
    //add interface set path
    uvm_config_db#(virtual spi_if)::set(null,"*************","spi_vif",spi_vif);
    uvm_config_db#(virtual apb_if)::set(null,"*************","apb_vif",apb_vif);
  end

  initial begin
    $fsdbDumpfile(spi_top_tb.fsdb);
    $fsdbDumpvars();
    $fsdbDumpSVA();
  end

endmodule: spi_test_top
`endif //SPI_TEST_TOP_SV