//
//Note:
//This file is generated by Mako Template
//spi_scoreboard
//
`ifndef SPI_SCOREBOARD_SVH
`define SPI_SCOREBOARD_SVH
class spi_scoreboard extends uvm_scoreboard;
  `uvm_component_utils(spi_scoreboard)

  uvm_block_get_block_port #({i}_seq_item) spi_mst_port;
  uvm_block_get_block_port #({i}_seq_item) spi_slv_port;
  uvm_block_get_block_port #({i}_seq_item) apb_port;

  spi_mst_seq_item spi_mst_queue[$];
  spi_slv_seq_item spi_slv_queue[$];
  apb_seq_item apb_queue[$];

  extern virtual function void new(string name = "spi_scoreboard",uvm_component parent = null);
  extern virtual function void build_phase(uvm_phase phase);
  extern virtual function void run_phase(uvm_phase phase);

endclass: spi_scoreboard

function void spi_scoreboard::new(string name = "spi_scoreboard",uvm_component parent = null);
  super.new(name,parent);
endfunction:new

function void spi_scoreboard::build_phase(uvm_phase phase);
  super.build_phase();

endfunction: build_phase

function void spi_scoreboard::run_phase(uvm_phase phase);
  super.run_phase(phase);

endfunction: run_phase
`endif //SPI_SCOREBOARD_SVH
