//
//Note:
//This file is generated by Mako Template
//spi
//
`ifndef SPI_ENV_SVH
`define SPI_ENV_SVH
class spi_env extends uvm_env;
  `uvm_component_utils(spi_env)

  virtual spi_if spi_vif;
  virtual apb_if apb_vif;

  apb_agent apb_agt;
  spi_mst_agent spi_mst_agt;
  spi_slv_agent spi_slv_agt;

  spi_scoreboard spi_scb;
  spi_coverage spi_cvr;
  ral_block_reg_model p_rm;

  uvm_tlm_analysis_fifo #(spi_mst_seq_item) spi_mst_fifo;
  uvm_tlm_analysis_fifo #(spi_slv_seq_item) spi_slv_fifo;
  uvm_tlm_analysis_fifo #(apb_seq_item) apb_fifo;

  extern funtion new(string name = "spi",uvm_component parent);
  extern function void build_phase(uvm_phase phase);
  extern function void connect_phase(uvm_phase phase);

endclass: spi_env

function spi::new(string name = "spi_env",uvm_component parent);
  super.new(name, parent);
endfunction

function void spi_env::build_phase(uvm_phase phase);
  super.build_phase(phase);

  apb_agt = apb_agent::type_id::creat("apb_agt",this);
  apb_agt.is_active = UVM_ACTIVE;
  spi_mst_agt = spi_mst_agent::type_id::creat("spi_mst_agt",this);
  spi_mst_agt.is_active = UVM_ACTIVE;
  spi_slv_agt = spi_slv_agent::type_id::creat("spi_slv_agt",this);
  spi_slv_agt.is_active = UVM_ACTIVE;

  spi_scb = spi_scoreboard::type_id::creat("spi_scb",this);
  spi_cvr = spi_coverage::type_id::create("spi_cvr",this);
  p_rm = ral_block_reg_model::type_id::type_id::create("p_rm",this);

  spi_mst_fifo = new("spi_mst_fifo",this);
  spi_slv_fifo = new("spi_slv_fifo",this);
  apb_fifo = new("apb_fifo",this);

  if(!uvm_config_db#(virtual spi_if)::get(this, "", "spi_vif", spi_vif))
    `uvm_fatal("build_phase","No get spi_if!!!!")
  if(!uvm_config_db#(virtual apb_if)::get(this, "", "apb_vif", apb_vif))
    `uvm_fatal("build_phase","No get apb_if!!!!")

endfunction:build_phase

function void spi_env::connect_phase(uvm_phase phase);
  super.connect_phase(phase);
endfunction:connect_phase
`endif //SPI_ENV_SVH