//
//Note:
//This file is generated by Mako Template
//spi_virtual_sqr
//
`ifndef SPI_VIRTUAL_SQR_SVH
`define SPI_VIRTUAL_SQR_SVH
class spi_virtual_sqr extends uvm_sequencer;

  //add sequencer:
  ral_block_reg_model p_rm;
  spi_mst_sequencer p_spi_mst_sqr;
  spi_slv_sequencer p_spi_slv_sqr;
  apb_sequencer p_apb_sqr;
  spi_if p_spi_vif;
  apb_if p_apb_vif;

  function new(string name = "spi_virtual_sqr",uvm_component parent);
    super.new(name, parent);
  endfunction:new

  `uvm_component_utils(spi_virtual_sqr)
 endclass: spi_virtual_sqr
`endif //SPI_VIRTUAL_SQR_SVH