//
//Note:
//This file is generated by Mako Template
//spi_env_pkg
//

`ifndef spi_ENV_PKG
`define spi_ENV_PKG

package spi_env_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

   `include "../spi_env/spi_scoreboard.svh"
   `include "../spi_env/spi_virtual_sqr.svh"
   `include "../spi_env/spi_env.svh"
   `include "../spi_env/spi_basic_test.svh"

endpackage: spi_env_pkg
`endif //spi_ENV_PKG