//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// ${env_name} vseqs pkg
//

`ifndef ${env_name}_VSEQS_PKG
`define ${env_name}_VSEQS_PKG

package ${env_name}_vseqs_pkg

  import uvm_pkg::*;
  `include "uvm_maros.svh"

  `include "../${env_name}_virtual_seqs/${env_name}_vseqs_name.svh"

endpackage: ${env_name}_vseqs_pkg
`endif //${env_name}_VSEQS_PKG