//
//Note:
//This file is generated by Mako Template
//${env_name}_vseqs_base
//

`ifndef ${env_name.upper()}_VSEQS_BASE_SVH
`define ${env_name.upper()}_VSEQSBASE_SVH

class ${env_name}_vseqs_base extends uvm_sequence;
  `uvm_object_utils(${env_name}_vseqs_base)
  `uvm_declare_p_sequencer(${vsqr_name})

  function new(string name = "${env_name}_vseqs_base");
    super.new(name);
  endfunction

  extern virtual task body();

endclass: ${env_name}_vseqs_base

task ${env_name}_vseqs_base::task();


endtask: task
`endif //${env_name.upper()}_VSEQS_BASE_SVH