//
//Note:
//This file is generated by Mako Template
//spi_vseqs_base
//

`ifndef SPI_VSEQS_BASE_SVH
`define SPI_VSEQSBASE_SVH

class spi_vseqs_base extends uvm_sequence;
  `uvm_object_utils(spi_vseqs_base)
  `uvm_declare_p_sequencer(spi_virtual_sqr)

  function new(string name = "spi_vseqs_base");
    super.new(name);
  endfunction

  extern virtual task body();

endclass: spi_vseqs_base

task spi_vseqs_base::task();


endtask: task
`endif //SPI_VSEQS_BASE_SVH