//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// spi vseqs pkg
//

`ifndef spi_VSEQS_PKG
`define spi_VSEQS_PKG

package spi_vseqs_pkg

  import uvm_pkg::*;
  `include "uvm_maros.svh"

  `include "../spi_virtual_seqs/spi_vseqs_name.svh"

endpackage: spi_vseqs_pkg
`endif //spi_VSEQS_PKG