//
//Note:
//This file is generated by Mako Template
//spi_seqs_pkg
//

`ifndef spi_SEQS_PKG
`define spi_SEQS_PKG

package spi_SEQS_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

   `include "../spi_sequences/spi_basic_seq.svh"


endpackage: spi_SEQS_pkg
`endif //spi_SEQS_PKG