//
//Note:
//This file is generated by Mako Template
//${env_name}_test_top
//
`ifndef ${env_name.upper()}_TEST_TOP_SV
`define ${env_name.upper()}_TEST_TOP_SV
module ${env_name}_test_top;

  %for i in interface:
  ${i}_if ${i}_vif;
  %endfor

  //add Dut top


  initial begin
    run_test();
  end

  initial begin
    //add interface set path
    %for i in interface:
    uvm_config_db#(virtual ${i}_if)::set(null,"*************","${i}_vif",${i}_vif);
    %endfor
  end

  initial begin
    $fsdbDumpfile(${env_name}_top_tb.fsdb);
    $fsdbDumpvars();
    $fsdbDumpSVA();
  end

endmodule: ${env_name}_test_top
`endif //${env_name.upper()}_TEST_TOP_SV