//
//Note:
//This file is generated by Mako Template
//${env_name}_seqs_pkg
//

`ifndef ${env_name}_SEQS_PKG
`define ${env_name}_SEQS_PKG

package ${env_name}_SEQS_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

   `include "../${env_name}_sequences/${env_name}_basic_seq.svh"


endpackage: ${env_name}_SEQS_pkg
`endif //${env_name}_SEQS_PKG