//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// ${env_name} testcases pkg
//

`ifndef ${env_name.upper()}_TESTCASES_PKG
`define ${env_name.upper()}_TESTCASES_PKG

package ${env_name}_testcases_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  `include "../${env_name}_testcases/${env_name}_basic_testcase.svh"

endpackage: ${env_name}_testcases_pkg
`endif //${env_name.upper()}_TESTCASES_PKG