//
//Note:
//This file is generated by Mako Template
//${env_name}_basic_testcase
//
`ifndef ${env_name.upper()}_BASIC_TESTCASE
`define ${env_name.upper()}_BASIC_TESTCASE

class ${env_name}_basic_testcase ${env_name}_basic_test;

  `uvm_component_utils(${env_name}_basic_testcase)

  uvm_cmdline_processor clp;
  string arg;

  function new(string name = "${env_name}_basic_test", uvm_component parent = null);
    super.new(name);

    //get cmd parameter
    if(clp.get_arg_value("+****=",this.arg))
    begin
      this.**** = this.arg.atoi();
      `uvm_info("new",$sformatf("**** = %h",****),UVM_LOW)
    end

  endfunction

  extern virtual funciton void build_phase(uvm_phase);

endclass: ${env_name}_basic_testcase

function void ${env_name}_basic_testcase::build_phase(uvm_phase phase);
  super.build_phase(phase);

endfunction: build_phase
`endif //${env_name.upper()}_BASIC_TESTCASE